// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Plugin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Ice_Plugin_h__
#define __Ice_Plugin_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/LoggerF.h>
#include <Ice/BuiltinSequences.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef ICE_API
#   if defined(ICE_STATIC_LIBS)
#       define ICE_API /**/
#   elif defined(ICE_API_EXPORTS)
#       define ICE_API ICE_DECLSPEC_EXPORT
#   else
#       define ICE_API ICE_DECLSPEC_IMPORT
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace Ice
{

class Plugin;
class PluginManager;

}

namespace Ice
{

class ICE_CLASS(ICE_API) Plugin
{
public:

    ICE_MEMBER(ICE_API) virtual ~Plugin();

    virtual void initialize() = 0;

    virtual void destroy() = 0;
};

class ICE_CLASS(ICE_API) PluginManager
{
public:

    ICE_MEMBER(ICE_API) virtual ~PluginManager();

    virtual void initializePlugins() = 0;

    virtual ::Ice::StringSeq getPlugins() = 0;

    virtual ::std::shared_ptr<::Ice::Plugin> getPlugin(const ::std::string&) = 0;

    virtual void addPlugin(const ::std::string&, const ::std::shared_ptr<::Ice::Plugin>&) = 0;

    virtual void destroy() = 0;
};

}

namespace Ice
{

}

namespace Ice
{

using PluginPtr = ::std::shared_ptr<Plugin>;

using PluginManagerPtr = ::std::shared_ptr<PluginManager>;

}

#else // C++98 mapping

namespace Ice
{

class Plugin;
ICE_API ::Ice::LocalObject* upCast(::Ice::Plugin*);
typedef ::IceInternal::Handle< ::Ice::Plugin> PluginPtr;

class PluginManager;
ICE_API ::Ice::LocalObject* upCast(::Ice::PluginManager*);
typedef ::IceInternal::Handle< ::Ice::PluginManager> PluginManagerPtr;

}

namespace Ice
{

class ICE_API Plugin : public virtual ::Ice::LocalObject
{
public:

    typedef PluginPtr PointerType;

    virtual ~Plugin();

    virtual void initialize() = 0;

    virtual void destroy() = 0;
};

inline bool operator==(const Plugin& lhs, const Plugin& rhs)
{
    return static_cast<const ::Ice::LocalObject&>(lhs) == static_cast<const ::Ice::LocalObject&>(rhs);
}

inline bool operator<(const Plugin& lhs, const Plugin& rhs)
{
    return static_cast<const ::Ice::LocalObject&>(lhs) < static_cast<const ::Ice::LocalObject&>(rhs);
}

class ICE_API PluginManager : public virtual ::Ice::LocalObject
{
public:

    typedef PluginManagerPtr PointerType;

    virtual ~PluginManager();

    virtual void initializePlugins() = 0;

    virtual ::Ice::StringSeq getPlugins() = 0;

    virtual ::Ice::PluginPtr getPlugin(const ::std::string&) = 0;

    virtual void addPlugin(const ::std::string&, const ::Ice::PluginPtr&) = 0;

    virtual void destroy() = 0;
};

inline bool operator==(const PluginManager& lhs, const PluginManager& rhs)
{
    return static_cast<const ::Ice::LocalObject&>(lhs) == static_cast<const ::Ice::LocalObject&>(rhs);
}

inline bool operator<(const PluginManager& lhs, const PluginManager& rhs)
{
    return static_cast<const ::Ice::LocalObject&>(lhs) < static_cast<const ::Ice::LocalObject&>(rhs);
}

}

namespace Ice
{

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
