// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Properties.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Ice_Properties_h__
#define __Ice_Properties_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/PropertiesAdmin.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifndef ICE_API
#   if defined(ICE_STATIC_LIBS)
#       define ICE_API /**/
#   elif defined(ICE_API_EXPORTS)
#       define ICE_API ICE_DECLSPEC_EXPORT
#   else
#       define ICE_API ICE_DECLSPEC_IMPORT
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace Ice
{

class Properties;

}

namespace Ice
{

class ICE_CLASS(ICE_API) Properties
{
public:

    ICE_MEMBER(ICE_API) virtual ~Properties();

    virtual ::std::string getProperty(const ::std::string&) = 0;

    virtual ::std::string getPropertyWithDefault(const ::std::string&, const ::std::string&) = 0;

    virtual int getPropertyAsInt(const ::std::string&) = 0;

    virtual int getPropertyAsIntWithDefault(const ::std::string&, int) = 0;

    virtual ::Ice::StringSeq getPropertyAsList(const ::std::string&) = 0;

    virtual ::Ice::StringSeq getPropertyAsListWithDefault(const ::std::string&, const ::Ice::StringSeq&) = 0;

    virtual ::Ice::PropertyDict getPropertiesForPrefix(const ::std::string&) = 0;

    virtual void setProperty(const ::std::string&, const ::std::string&) = 0;

    virtual ::Ice::StringSeq getCommandLineOptions() = 0;

    virtual ::Ice::StringSeq parseCommandLineOptions(const ::std::string&, const ::Ice::StringSeq&) = 0;

    virtual ::Ice::StringSeq parseIceCommandLineOptions(const ::Ice::StringSeq&) = 0;

    virtual void load(const ::std::string&) = 0;

    virtual ::std::shared_ptr<::Ice::Properties> clone() = 0;
};

}

namespace Ice
{

}

namespace Ice
{

using PropertiesPtr = ::std::shared_ptr<Properties>;

}

#else // C++98 mapping

namespace IceProxy
{

}

namespace Ice
{

class Properties;
ICE_API ::Ice::LocalObject* upCast(::Ice::Properties*);
typedef ::IceInternal::Handle< ::Ice::Properties> PropertiesPtr;

}

namespace IceProxy
{

}

namespace Ice
{

class ICE_API Properties : public virtual ::Ice::LocalObject
{
public:

    typedef PropertiesPtr PointerType;

    virtual ~Properties();

    virtual ::std::string getProperty(const ::std::string&) = 0;

    virtual ::std::string getPropertyWithDefault(const ::std::string&, const ::std::string&) = 0;

    virtual ::Ice::Int getPropertyAsInt(const ::std::string&) = 0;

    virtual ::Ice::Int getPropertyAsIntWithDefault(const ::std::string&, ::Ice::Int) = 0;

    virtual ::Ice::StringSeq getPropertyAsList(const ::std::string&) = 0;

    virtual ::Ice::StringSeq getPropertyAsListWithDefault(const ::std::string&, const ::Ice::StringSeq&) = 0;

    virtual ::Ice::PropertyDict getPropertiesForPrefix(const ::std::string&) = 0;

    virtual void setProperty(const ::std::string&, const ::std::string&) = 0;

    virtual ::Ice::StringSeq getCommandLineOptions() = 0;

    virtual ::Ice::StringSeq parseCommandLineOptions(const ::std::string&, const ::Ice::StringSeq&) = 0;

    virtual ::Ice::StringSeq parseIceCommandLineOptions(const ::Ice::StringSeq&) = 0;

    virtual void load(const ::std::string&) = 0;

    virtual ::Ice::PropertiesPtr clone() = 0;
};

inline bool operator==(const Properties& lhs, const Properties& rhs)
{
    return static_cast<const ::Ice::LocalObject&>(lhs) == static_cast<const ::Ice::LocalObject&>(rhs);
}

inline bool operator<(const Properties& lhs, const Properties& rhs)
{
    return static_cast<const ::Ice::LocalObject&>(lhs) < static_cast<const ::Ice::LocalObject&>(rhs);
}

}

namespace Ice
{

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
